-- Run inside the migration transaction, then ROLLBACK. No fixture data is retained.
DO $$
DECLARE eid uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); d uuid:=gen_random_uuid();
  sid uuid:=gen_random_uuid(); admin_id uuid; t1 uuid; t2 uuid; snap jsonb; rev text; proposal jsonb; version public.endurance_planning_versions; stints jsonb; failed boolean;
BEGIN
  SELECT user_id INTO admin_id FROM public.user_roles WHERE role::text='super_admin' LIMIT 1;
  IF admin_id IS NULL THEN RAISE EXCEPTION 'Test needs an existing super admin'; END IF;
  PERFORM set_config('request.jwt.claim.sub',admin_id::text,true);
  INSERT INTO public.endurance_events(id,name,circuit,start_at,end_at,selected_car_id,max_drivers_per_car) VALUES(eid,'Transactional team workflow test','test','2026-10-01 12:00Z','2026-10-01 13:00Z','test-car',8);
  INSERT INTO public.endurance_registrations(event_id,user_id,status,max_total_minutes,max_stints) SELECT eid,id,'provisional',60,2 FROM unnest(ARRAY[a,b,c,d]) id;
  INSERT INTO public.endurance_availability(event_id,user_id,start_at,end_at,type) SELECT eid,id,'2026-10-01 12:00Z','2026-10-01 13:00Z','available' FROM unnest(ARRAY[a,b,c,d]) id;
  snap:=public.endurance_team_workspace(eid);rev:=snap->>'revision';
  proposal:=jsonb_build_array(jsonb_build_object('name','Competitive','capacity',2,'approach','competitive','userIds',jsonb_build_array(a,b)),jsonb_build_object('name','Fun','capacity',4,'approach','fun','userIds',jsonb_build_array(c,d)));
  PERFORM public.endurance_apply_team_proposal(eid,rev,proposal);
  SELECT id INTO t1 FROM public.endurance_teams WHERE event_id=eid AND name='Competitive';
  SELECT id INTO t2 FROM public.endurance_teams WHERE event_id=eid AND name='Fun';
  IF (SELECT count(*) FROM public.endurance_team_members WHERE event_id=eid)<>4 THEN RAISE EXCEPTION 'Roster not saved'; END IF;
  failed:=false;BEGIN PERFORM public.endurance_apply_team_proposal(eid,rev,proposal);EXCEPTION WHEN serialization_failure THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Stale proposal accepted'; END IF;
  rev:=public.endurance_team_workspace(eid)->>'revision';
  failed:=false;BEGIN PERFORM public.endurance_manage_team(eid,rev,jsonb_build_object('kind','move','user_id',c,'team_id',t1));EXCEPTION WHEN OTHERS THEN failed:=true;END;
  IF NOT failed OR (SELECT team_id FROM public.endurance_team_members WHERE event_id=eid AND user_id=c)<>t2 THEN RAISE EXCEPTION 'Full team move was not atomic'; END IF;
  PERFORM public.endurance_manage_team(eid,rev,jsonb_build_object('kind','move','user_id',b,'team_id',t2));
  IF (SELECT count(*) FROM public.endurance_team_members WHERE event_id=eid AND user_id=b)<>1 THEN RAISE EXCEPTION 'Duplicate membership after move'; END IF;
  PERFORM public.endurance_manage_team(eid,public.endurance_team_workspace(eid)->>'revision',jsonb_build_object('kind','move','user_id',b,'team_id',t1));
  failed:=false;BEGIN UPDATE public.endurance_events SET max_drivers_per_car=1 WHERE id=eid;EXCEPTION WHEN OTHERS THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Unsafe ceiling reduction accepted'; END IF;
  stints:=jsonb_build_array(jsonb_build_object('driverId',a,'actualStartAt','2026-10-01T12:00:00Z','actualEndAt','2026-10-01T12:30:00Z'),jsonb_build_object('driverId',b,'actualStartAt','2026-10-01T12:30:00Z','actualEndAt','2026-10-01T13:00:00Z'));
  version:=public.endurance_publish_plan(eid,t1,'Validated plan',stints,jsonb_build_array(jsonb_build_object('user_id',a,'status','unseen'),jsonb_build_object('user_id',b,'status','unseen')));
  IF (SELECT plan_needs_review FROM public.endurance_teams WHERE id=t1) THEN RAISE EXCEPTION 'Review status was not reset on validation'; END IF;
  UPDATE public.endurance_registrations SET max_total_minutes=10 WHERE event_id=eid AND user_id=a;
  IF NOT (SELECT plan_needs_review FROM public.endurance_teams WHERE id=t1) THEN RAISE EXCEPTION 'Changed driving limits did not invalidate plan'; END IF;
  failed:=false;BEGIN UPDATE public.endurance_confirmations SET status='accepted' WHERE version_id=version.id AND user_id=a;EXCEPTION WHEN OTHERS THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Outdated confirmation accepted'; END IF;
  failed:=false;BEGIN PERFORM public.endurance_publish_plan(eid,t1,'Invalid limits',stints,'[]');EXCEPTION WHEN OTHERS THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Invalid driving limit published'; END IF;
  IF NOT (SELECT published FROM public.endurance_planning_versions WHERE id=version.id) THEN RAISE EXCEPTION 'Failed publication lost previous version'; END IF;
  INSERT INTO public.endurance_practice_sessions(id,event_id,label,ended_at,conditions) VALUES(sid,eid,'Practice identity test',now(),'wet');
  INSERT INTO public.endurance_practice_laps(session_id,event_id,user_id,car_id,circuit,lap_seconds) SELECT sid,eid,a,'test-car','test',100 FROM generate_series(1,10);
  INSERT INTO public.endurance_practice_laps(session_id,event_id,user_id,car_id,circuit,lap_seconds) VALUES(sid,eid,a,'wrong-car','test',50);
  IF public.endurance_sync_practice_pace(sid,'test-car')<>1 THEN RAISE EXCEPTION 'Practice sync failed'; END IF;
  PERFORM public.endurance_sync_practice_pace(sid,'test-car');
  IF (SELECT count(*) FROM public.endurance_pace_entries WHERE practice_session_id=sid)<>1 THEN RAISE EXCEPTION 'Practice re-sync duplicated pace'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.endurance_pace_entries WHERE practice_session_id=sid AND average_lap_seconds=100 AND valid_laps=10 AND consistency_seconds=0 AND conditions='wet') THEN RAISE EXCEPTION 'Wrong car or conditions contaminated practice'; END IF;
  PERFORM set_config('request.jwt.claim.sub',a::text,true);
  failed:=false;BEGIN PERFORM public.endurance_team_workspace(eid);EXCEPTION WHEN insufficient_privilege THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Participant accessed manager snapshot'; END IF;
  PERFORM set_config('request.jwt.claim.sub','',true);
  failed:=false;BEGIN PERFORM public.endurance_apply_team_proposal(eid,rev,proposal);EXCEPTION WHEN insufficient_privilege THEN failed:=true;END;
  IF NOT failed THEN RAISE EXCEPTION 'Anonymous proposal accepted'; END IF;
  RAISE NOTICE 'PASS: mixed sizes, atomic moves, capacity, stale revision, publication validation, invalidation, practice identity/idempotency, permissions';
END;
$$;
