export const IRACING_TRACKS = [...new Set([
  "Adelaide Street Circuit",
  "Algarve International Circuit",
  "Algarve International Circuit - Grand Prix",
  "Algarve International Circuit - Grand Prix - Chicanes",
  "Algarve International Circuit - Moto",
  "Algarve International Circuit - Moto - Chicanes",
  "Auto Club Speedway",
  "Auto Club Speedway - Oval",
  "Auto Club Speedway - Competition",
  "Auto Club Speedway - Interior",
  "Auto Club Speedway - Moto",
  "Autódromo Hermanos Rodríguez (Mexico City)",
  "Autódromo Hermanos Rodríguez (Mexico City) - Grand Prix",
  "Autódromo Hermanos Rodríguez (Mexico City) - Grand Prix Historic",
  "Autódromo Hermanos Rodríguez (Mexico City) - National",
  "Autódromo Hermanos Rodríguez (Mexico City) - National Historic",
  "Autódromo Hermanos Rodríguez (Mexico City) - EV Circuit",
  "Autódromo Hermanos Rodríguez (Mexico City) - Oval",
  "Autódromo Hermanos Rodríguez (Mexico City) - Oval Stadium",
  "Autodromo Internazionale del Mugello - Short",
  "Autodromo Internazionale Enzo e Dino Ferrari",
  "Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix",
  "Autodromo Internazionale Enzo e Dino Ferrari - Moto",
  "Autódromo José Carlos Pace",
  "Autódromo José Carlos Pace - Grand Prix",
  "Autódromo José Carlos Pace - Moto",
  "Autodromo Nazionale Monza",
  "Autodromo Nazionale Monza - Grand Prix",
  "Autodromo Nazionale Monza - GP without chicanes",
  "Autodromo Nazionale Monza - GP without first chicane",
  "Autodromo Nazionale Monza - Combined",
  "Autodromo Nazionale Monza - Combined without chicanes",
  "Autodromo Nazionale Monza - Combined without first chicane",
  "Autodromo Nazionale Monza - Junior",
  "Autodromo Nazionale Monza - Oval - Left turning",
  "Autodromo Nazionale Monza - Oval - Right turning",
  "Barber Motorsports Park",
  "Barber Motorsports Park - Full Course",
  "Barber Motorsports Park - Short A",
  "Barber Motorsports Park - Short B",
  "Bark River International Raceway",
  "Brands Hatch Circuit",
  "Brands Hatch Circuit - Grand Prix",
  "Brands Hatch Circuit - Indy",
  "Brands Hatch Circuit - Rallycross",
  "Bristol Motor Speedway",
  "Bristol Motor Speedway - Dual Pit Roads",
  "Bristol Motor Speedway - Single Pit Road",
  "Bristol Motor Speedway - Dirt",
  "Bristol Motor Speedway - Dirt - 2021",
  "Cadwell Park Circuit",
  "Cadwell Park Circuit - Full",
  "Cadwell Park Circuit - Club",
  "Cadwell Park Circuit - Moto",
  "Cadwell Park Circuit - Woodlands",
  "Canadian Tire Motorsports Park",
  "Cedar Lake Speedway",
  "Centripetal Circuit",
  "Charlotte Motor Speedway",
  "Charlotte Motor Speedway - Oval - 2018",
  "Charlotte Motor Speedway - Roval",
  "Charlotte Motor Speedway - Roval Long",
  "Charlotte Motor Speedway - Roval - 2018",
  "Charlotte Motor Speedway - Legends Oval",
  "Charlotte Motor Speedway - Legends RC Oval Long",
  "Charlotte Motor Speedway - Legends RC Oval Medium",
  "Charlotte Motor Speedway - Legends RC Oval Short",
  "Charlotte Motor Speedway - Rallycross",
  "Chicago Street Course",
  "Chicago Street Course - 2023 Cup",
  "Chicago Street Course - Prototype",
  "Chicagoland Speedway",
  "Chili Bowl",
  "Circuit de Barcelona Catalunya",
  "Circuit de Barcelona-Catalunya - Grand Prix",
  "Circuit de Barcelona-Catalunya - National",
  "Circuit de Barcelona-Catalunya - Moto",
  "Circuit de Barcelona-Catalunya - Club",
  "Circuit de Barcelona-Catalunya - Historic",
  "Circuit de Barcelona-Catalunya - Rallycross",
  "Circuit de Lédenon",
  "Circuit de Nevers Magny-Cours",
  "Circuit de Nevers Magny-Cours - Grand Prix",
  "Circuit de Spa-Francorchamps",
  "Circuit de Spa-Francorchamps - Grand Prix Pits",
  "Circuit de Spa-Francorchamps - Classic Pits",
  "Circuit de Spa-Francorchamps - Endurance",
  "Circuit de Spa-Francorchamps - Bike",
  "Circuit de Spa-Francorchamps - Grand Prix Pits - 2010",
  "Circuit de Spa-Francorchamps - Classic Pits - 2010",
  "Circuit de Spa-Francorchamps - Endurance - 2010",
  "Circuit des 24 Heures du Mans",
  "Circuit des 24 Heures du Mans - 24 Heures du Man",
  "Circuit des 24 Heures du Mans - Historic",
  "Circuit Gilles Villeneuve",
  "Circuit of the Americas",
  "Circuit of the Americas - Grand Prix",
  "Circuit of the Americas - East",
  "Circuit of the Americas - West",
  "Circuit Park Zandvoort",
  "Circuit Park Zandvoort - Grand Prix - 2009",
  "Circuit Park Zandvoort - National - 2009",
  "Circuit Park Zandvoort - Chicane - 2009",
  "Circuit Park Zandvoort - Club - 2009",
  "Circuit Park Zandvoort - Oostelijk - 2009",
  "Circuit Zandvoort",
  "Circuit Zandvoort - Grand Prix",
  "Circuit Zandvoort - Grand Prix w/2 Chicane",
  "Circuit Zandvoort - Nationaal",
  "Circuit Zandvoort - Oostelijk",
  "Circuit Zolder",
  "Circuit Zolder - Grand Prix",
  "Circuit Zolder - Alternate",
  "Circuito de Jerez - Ángel Nieto",
  "Circuito de Jerez - Ángel Nieto - Grand Prix",
  "Circuito de Jerez - Ángel Nieto - Moto",
  "Circuito de Navarra",
  "Circuito de Navarra - Speed Circuit",
  "Circuito de Navarra - Speed Circuit - Medium",
  "Circuito de Navarra - Speed Circuit - Short",
  "Concord Speedway",
  "Crandon International Raceway",
  "Crandon International Raceway - Full",
  "Crandon International Raceway - Short",
  "Darlington Raceway",
  "Daytona International Speedway",
  "Daytona International Speedway - Oval",
  "Daytona International Speedway - Road Course",
  "Daytona International Speedway - NASCAR Road Course",
  "Daytona International Speedway - Moto",
  "Daytona International Speedway - Short",
  "Daytona International Speedway - Oval - 2008",
  "Daytona International Speedway - Road Course - 2008",
  "Daytona International Speedway - Moto - 2008",
  "Daytona International Speedway - Short - 2008",
  "Daytona Rallycross and Dirt Road",
  "Daytona Rallycross and Dirt Road - Dirt Road Long",
  "Daytona Rallycross and Dirt Road - Dirt Road Short",
  "Daytona Rallycross and Dirt Road - Rallycross Long",
  "Daytona Rallycross and Dirt Road - Rallycross Short",
  "Detroit Grand Prix at Belle Isle",
  "Donington Park Racing Circuit",
  "Donington Park Racing Circuit - Grand Prix",
  "Donington Park Racing Circuit - National",
  "Dover Motor Speedway",
  "EchoPark Speedway (Atlanta)",
  "EchoPark Speedway (Atlanta) - Oval",
  "EchoPark Speedway (Atlanta) - Rallycross Long",
  "EchoPark Speedway (Atlanta) - Rallycross Short",
  "EchoPark Speedway (Atlanta) - Oval - 2008",
  "EchoPark Speedway (Atlanta) - Legends Oval - 2008",
  "EchoPark Speedway (Atlanta) - Road Course - 2008",
  "Eldora Speedway",
  "Fairbury Speedway",
  "Federated Auto Parts Raceway at I-55",
  "Firebird Motorsports Park",
  "Five Flags Speedway",
  "Fuji International Speedway",
  "Fuji International Speedway - Grand Prix",
  "Fuji International Speedway - No Chicane",
  "Hickory Motor Speedway",
  "Hockenheimring Baden-Württemberg",
  "Hockenheimring Baden-Württemberg - Grand Prix",
  "Hockenheimring Baden-Württemberg - National A",
  "Hockenheimring Baden-Württemberg - National B",
  "Hockenheimring Baden-Württemberg - Outer",
  "Hockenheimring Baden-Württemberg - PEC - East",
  "Hockenheimring Baden-Württemberg - PEC - Handling",
  "Hockenheimring Baden-Württemberg - PEC - Outer",
  "Hockenheimring Baden-Württemberg - PEC - West",
  "Hockenheimring Baden-Württemberg - Short A",
  "Hockenheimring Baden-Württemberg - Short B",
  "Homestead Miami Speedway",
  "Homestead Miami Speedway - Oval",
  "Homestead Miami Speedway - Open Wheel Oval",
  "Homestead Miami Speedway - Road Course A",
  "Homestead Miami Speedway - Road Course B",
  "Hungaroring Circuit",
  "Huset's Speedway",
  "Indianapolis Motor Speedway",
  "Indianapolis Motor Speedway - Oval",
  "Indianapolis Motor Speedway - Open Wheel Oval",
  "Indianapolis Motor Speedway - Road Course",
  "Indianapolis Motor Speedway - Bike",
  "Indianapolis Motor Speedway - Oval - 2009",
  "Indianapolis Motor Speedway - Open Wheel Oval - 2009",
  "Indianapolis Motor Speedway - Road Course - 2009",
  "Iowa Speedway",
  "Iowa Speedway - Oval",
  "Iowa Speedway - Oval - 2011",
  "Iowa Speedway - Road Course",
  "Iowa Speedway - Infield Road Course",
  "Iowa Speedway - Legends",
  "Iowa Speedway - Infield Legends",
  "Iowa Speedway - Rallycross",
  "iRacing Superspeedway",
  "Irwindale Speedway",
  "Irwindale Speedway - Outer",
  "Irwindale Speedway - Inner",
  "Irwindale Speedway - Outer - Inner",
  "Irwindale Speedway - Figure Eight",
  "Irwindale Speedway - Figure Eight Jump",
  "Kansas Speedway",
  "Kansas Speedway - Oval",
  "Kansas Speedway - Road Course",
  "Kansas Speedway - Infield Road Course",
  "Kentucky Speedway",
  "Kentucky Speedway - Oval",
  "Kevin Harvick's Kern Raceway",
  "Kevin Harvick's Kern Raceway - Asphalt Track",
  "Kevin Harvick's Kern Raceway - Legends",
  "Kevin Harvick's Kern Raceway - Dirt Track",
  "Kevin Harvick's Kern Raceway - Dirt Mini Oval",
  "Knockhill Racing Circuit",
  "Knockhill Racing Circuit - International",
  "Knockhill Racing Circuit - International Reverse",
  "Knockhill Racing Circuit - National",
  "Knockhill Racing Circuit - National Reverse",
  "Knockhill Racing Circuit - Tri-Oval",
  "Knockhill Racing Circuit - Rallycross",
  "Knoxville Raceway",
  "Kokomo Speedway",
  "Kokomo Speedway - Tires In",
  "Kokomo Speedway - Tires Out",
  "Langley Speedway",
  "Lanier National Speedway",
  "Lanier National Speedway - Asphalt",
  "Lanier National Speedway - Dirt",
  "Lånkebanen (Hell RX)",
  "Lånkebanen (Hell RX) - Club",
  "Lånkebanen (Hell RX) - Hell Rallycross",
  "Lånkebanen (Hell RX) - Rallycross Short",
  "Lånkebanen (Hell RX) - Road Long",
  "Lånkebanen (Hell RX) - Road Short",
  "Las Vegas Motor Speedway",
  "Las Vegas Motor Speedway - Infield Legends Oval",
  "Las Vegas Motor Speedway - Legends Oval",
  "Las Vegas Motor Speedway - Oval",
  "Las Vegas Motor Speedway - Road Course Combined",
  "Las Vegas Motor Speedway - Road Course Long",
  "Las Vegas Motor Speedway - Road Course Short",
  "Lernerville Speedway",
  "Limaland Motorsports Park",
  "Lime Rock Park",
  "Lime Rock Park - Chicanes",
  "Lime Rock Park - Classic",
  "Lime Rock Park - Grand Prix",
  "Lime Rock Park - School",
  "Lime Rock Park - West Bend Chicane",
  "Lincoln Speedway",
  "Long Beach Street Circuit",
  "Los Angeles Memorial Coliseum",
  "Lucas Oil Indianapolis Raceway Park",
  "Lucas Oil Indianapolis Raceway Park - Oval",
  "Lucas Oil Indianapolis Raceway Park - Rallycross",
  "Lucas Oil Speedway",
  "Lucas Oil Speedway - Dirt Oval",
  "Lucas Oil Speedway - Off Road",
  "Martinsville Speedway",
  "Miami International Autodrome",
  "Miami International Autodrome - Grand Prix",
  "Miami International Autodrome - Marina Loop",
  "Miami International Autodrome - MIA Loop",
  "Miami International Autodrome - Extended MIA Loop",
  "Miami International Autodrome - Extended Marina Loop",
  "Michigan International Speedway",
  "Mid-Ohio Sports Car Course",
  "Mid-Ohio Sports Car Course - Alt Oval",
  "Mid-Ohio Sports Car Course - Chicane",
  "Mid-Ohio Sports Car Course - Full Course",
  "Mid-Ohio Sports Car Course - Oval",
  "Mid-Ohio Sports Car Course - Short",
  "Millbridge Speedway",
  "Misano World Circuit Marco Simoncelli",
  "Misano World Circuit Marco Simoncelli - Club",
  "Misano World Circuit Marco Simoncelli - Grand Prix",
  "Misano World Circuit Marco Simoncelli - Grand Prix - Historic",
  "Misano World Circuit Marco Simoncelli - Grand Prix 2007",
  "Misano World Circuit Marco Simoncelli - Truck",
  "Mobility Resort Motegi",
  "Mobility Resort Motegi - East",
  "Mobility Resort Motegi - Grand Prix",
  "Mobility Resort Motegi - Oval",
  "Mobility Resort Motegi - West",
  "MotorLand Aragón",
  "MotorLand Aragón - Grand Prix",
  "MotorLand Aragón - Motorcycle Grand Prix",
  "MotorLand Aragón - Motorcycle National",
  "MotorLand Aragón - National",
  "MotorLand Aragón - Outer",
  "MotorLand Aragón - Touring Car",
  "MotorLand Aragón - West",
  "Motorsport Arena Oschersleben",
  "Motorsport Arena Oschersleben - Alternate",
  "Motorsport Arena Oschersleben - B Course",
  "Motorsport Arena Oschersleben - C Course",
  "Motorsport Arena Oschersleben - Grand Prix",
  "Mount Panorama Circuit",
  "Mount Washington Auto Road",
  "Mount Washington Auto Road - Descent",
  "Mount Washington Auto Road - Hillclimb",
  "Myrtle Beach Speedway",
  "Nashville Fairgrounds Speedway",
  "Nashville Fairgrounds Speedway - Mini",
  "Nashville Fairgrounds Speedway - Oval",
  "Nashville Superspeedway",
  "New Hampshire Motor Speedway",
  "New Hampshire Motor Speedway - Legends",
  "New Hampshire Motor Speedway - Oval",
  "New Hampshire Motor Speedway - Road Course",
  "New Hampshire Motor Speedway - Road Course with North Oval",
  "New Hampshire Motor Speedway - Road Course with South Oval",
  "New Jersey Motorsports Park",
  "New Jersey Motorsports Park - Thunderbolt",
  "New Jersey Motorsports Park - Thunderbolt w/both chicanes",
  "New Jersey Motorsports Park - Thunderbolt w/first chicane",
  "New Jersey Motorsports Park - Thunderbolt w/second chicane",
  "New Smyrna Speedway",
  "North Wilkesboro Speedway",
  "North Wilkesboro Speedway - 1987",
  "Nürburgring Combined",
  "Nürburgring Combined - Gesamtstrecke 24h",
  "Nürburgring Combined - Gesamtstrecke Long",
  "Nürburgring Combined - Gesamtstrecke Short w/o Arena",
  "Nürburgring Combined - Gesamtstrecke VLN",
  "Nürburgring Grand-Prix-Strecke",
  "Nürburgring Grand-Prix-Strecke - BES/WEC",
  "Nürburgring Grand-Prix-Strecke - Grand Prix",
  "Nürburgring Grand-Prix-Strecke - Grand Prix w/out Arena",
  "Nürburgring Grand-Prix-Strecke - Kurzanbindung w/out Arena",
  "Nürburgring Grand-Prix-Strecke - Müllenbachschleife",
  "Nürburgring Grand-Prix-Strecke - Sprintstrecke",
  "Nürburgring Nordschleife",
  "Nürburgring Nordschleife - Industriefahrten",
  "Nürburgring Nordschleife - Touristenfahrten",
  "Okayama International Circuit",
  "Okayama International Circuit - Full Course",
  "Okayama International Circuit - Short",
  "Oran Park Raceway",
  "Oran Park Raceway - Grand Prix",
  "Oran Park Raceway - Moto",
  "Oran Park Raceway - North",
  "Oran Park Raceway - North A",
  "Oran Park Raceway - North B",
  "Oran Park Raceway - South",
  "Oswego Speedway",
  "Oswego Speedway - Dirt",
  "Oswego Speedway - Mini Oval",
  "Oswego Speedway - Oval",
  "Oulton Park Circuit",
  "Oulton Park Circuit - Fosters",
  "Oulton Park Circuit - Fosters w/Hislop",
  "Oulton Park Circuit - International",
  "Oulton Park Circuit - Intl w/out Brittens",
  "Oulton Park Circuit - Intl w/out Chicane",
  "Oulton Park Circuit - Intl w/out Hislop",
  "Oulton Park Circuit - Island",
  "Oulton Park Circuit - Island Historic",
  "Oxford Plains Speedway",
  "Phillip Island Circuit",
  "Phoenix Raceway",
  "Phoenix Raceway - Oval",
  "Phoenix Raceway - Oval w/open Dogleg",
  "Pocono Raceway",
  "Portland International Raceway",
  "Portland International Raceway - Full",
  "Portland International Raceway - No Chicane",
  "Port Royal Speedway",
  "Red Bull Ring",
  "Red Bull Ring - Grand Prix",
  "Red Bull Ring - National",
  "Red Bull Ring - North",
  "Richmond Raceway",
  "Road America",
  "Road America - Bend",
  "Road America - Full",
  "Road Atlanta",
  "Road Atlanta - Club",
  "Road Atlanta - Full Course",
  "Road Atlanta - Short",
  "Rockingham Speedway",
  "Rockingham Speedway - Oval",
  "Rockingham Speedway - Infield Road Course",
  "Rockingham Speedway - Road Course",
  "Rockingham Speedway - Short Road Course",
  "Rudskogen Motorsenter",
  "Sachsenring",
  "Sandown International Motor Raceway",
  "Sebring International Raceway",
  "Sebring International Raceway - Club",
  "Sebring International Raceway - International",
  "Sebring International Raceway - Modified",
  "Shell V-Power Motorsport Park at The Bend",
  "Shell V-Power Motorsport Park at The Bend - International Circuit",
  "Shell V-Power Motorsport Park at The Bend - GT Circuit",
  "Shell V-Power Motorsport Park at The Bend - Sprint Circuit",
  "Shell V-Power Motorsport Park at The Bend - East Circuit",
  "Shell V-Power Motorsport Park at The Bend - South-West Circuit",
  "Shell V-Power Motorsport Park at The Bend - West Circuit",
  "Shell V-Power Motorsport Park at The Bend - West Plus Circuit",
  "Silverstone Circuit",
  "Silverstone Circuit - Grand Prix",
  "Silverstone Circuit - International",
  "Silverstone Circuit - National",
  "Slinger Speedway",
  "Slinger Speedway - Figure Eight",
  "Slinger Speedway - Oval",
  "Snetterton Circuit",
  "St. Petersburg Street Circuit",
  "St. Petersburg Grand Prix",
  "Snetterton Circuit - 100",
  "Snetterton Circuit - 200",
  "Snetterton Circuit - 300",
  "Sonoma Raceway",
  "Sonoma Raceway - NASCAR Long",
  "Sonoma Raceway - NASCAR Short",
  "Sonoma Raceway - Open Wheel 2008-2011",
  "Sonoma Raceway - Open Wheel 2012-2018",
  "Sonoma Raceway - Open Wheel pre-2008",
  "Sonoma Raceway - Rallycross",
  "South Boston Speedway",
  "Southern National Motorsports Park",
  "Stafford Motor Speedway",
  "Stafford Motor Speedway - Full Course",
  "Stafford Motor Speedway - Mini Mile",
  "Summit Point Raceway",
  "Summit Point Raceway - Jefferson Circuit",
  "Summit Point Raceway - Jefferson Reverse",
  "Summit Point Raceway - Oval",
  "Summit Point Raceway - School",
  "Summit Point Raceway - Short",
  "Summit Point Raceway - Summit Point Raceway",
  "Suzuka International Racing Course",
  "Suzuka International Racing Course - East",
  "Suzuka International Racing Course - Grand Prix",
  "Suzuka International Racing Course - Moto",
  "Suzuka International Racing Course - West",
  "Suzuka International Racing Course - West w/chicane",
  "Talladega Superspeedway",
  "Texas Motor Speedway",
  "Texas Motor Speedway - Legends Oval",
  "Texas Motor Speedway - Oval",
  "The Bullring",
  "The Dirt Track at Charlotte",
  "The Milwaukee Mile",
  "Thompson Speedway Motorsports Park",
  "Thruxton Circuit",
  "Tsukuba Circuit",
  "Tsukuba Circuit - 1000 - Chicane",
  "Tsukuba Circuit - 1000 - Full",
  "Tsukuba Circuit - 1000 - Outer",
  "Tsukuba Circuit - 1000 - Reverse",
  "Tsukuba Circuit - 2000 - Full",
  "Tsukuba Circuit - 2000 - Moto",
  "Tsukuba Circuit - 2000 - Short",
  "USA International Speedway",
  "USA International Speedway - Asphalt",
  "USA International Speedway - Dirt",
  "Virginia International Raceway",
  "Virginia International Raceway - Full Course",
  "Virginia International Raceway - Grand Course",
  "Virginia International Raceway - North Course",
  "Virginia International Raceway - Patriot Course",
  "Virginia International Raceway - South Course",
  "Volusia Speedway Park",
  "Watkins Glen International",
  "Watkins Glen International - Boot",
  "Watkins Glen International - Classic",
  "Watkins Glen International - Classic Boot",
  "Watkins Glen International - Cup",
  "WeatherTech Raceway Laguna Seca",
  "WeatherTech Raceway Laguna Seca - School",
  "Weedsport Speedway",
  "Wild West Motorsports Park",
  "Williams Grove Speedway",
  "Willow Springs International Raceway",
  "Winton Motor Raceway",
  "Winton Motor Raceway - Club",
  "Winton Motor Raceway - National",
  "Winton Motor Raceway - Rallycross",
  "World Wide Technology Raceway (Gateway)",
  "World Wide Technology Raceway (Gateway) - Oval",
  "World Wide Technology Raceway (Gateway) - Road Course",
  "World Wide Technology Raceway (Gateway) - 2025 - Oval",
  "[Legacy] Charlotte Motor Speedway - 2008",
  "[Legacy] Charlotte Motor Speedway - 2008 - Infield Road Course",
  "[Legacy] Charlotte Motor Speedway - 2008 - Legends Oval",
  "[Legacy] Charlotte Motor Speedway - 2008 - Oval",
  "[Legacy] Charlotte Motor Speedway - 2008 - Road Course",
  "[Legacy] Kentucky Speedway - 2011",
  "[Legacy] Kentucky Speedway - Legends",
  "[Legacy] Kentucky Speedway - Oval",
  "[Legacy] Michigan International Speedway - 2009",
  "[Legacy] Phoenix Raceway - 2008",
  "[Legacy] Phoenix Raceway - 2008 - Dirt Road",
  "[Legacy] Phoenix Raceway - 2008 - Oval",
  "[Legacy] Silverstone Circuit - 2008 - Historical Grand Prix",
  "[Legacy] Silverstone Circuit - 2008 - International",
  "[Legacy] Silverstone Circuit - 2008 - National",
  "[Legacy] Silverstone Circuit - 2008 - Southern",
  "[Legacy] Texas Motor Speedway - 2009",
  "[Legacy] Texas Motor Speedway - 2009 - Legends Oval",
  "[Legacy] Texas Motor Speedway - 2009 - Oval",
  "[Legacy] Texas Motor Speedway - 2009 - Road Course Combined",
  "[Legacy] Texas Motor Speedway - 2009 - Road Course Long",
  "[Legacy] Texas Motor Speedway - 2009 - Road Course Short A",
  "[Legacy] Texas Motor Speedway - 2009 - Road Course Short B",
])].sort();
