import { CalendarClock, Car, CheckCircle2, Clock3, ShieldCheck, Users } from "lucide-react";
import { useEnduranceStore } from "../core/EnduranceStore";
import { canManageEvent, formatAmsterdam, getRegistration } from "../core/selectors";
import type { EnduranceEvent, RegistrationStatus } from "../core/types";
import { Panel, SectionHeading, StatusPill, inputClass } from "../shared/ui";
import { getEnduranceCar } from "../core/carCatalog";
import { VehicleVotePanel } from "./VehicleVotePanel";

export const OverviewPanel = ({ event }: { event: EnduranceEvent }) => {
  const { state, activePersona, dispatch } = useEnduranceStore();
  const registration = getRegistration(state, event.id, activePersona.id);
  const team = state.teams.find((candidate) => candidate.eventId === event.id && state.teamMembers.some((member) => member.teamId === candidate.id && member.userId === activePersona.id));
  const nextStint = state.stints.filter((stint) => stint.eventId === event.id && stint.driverId === activePersona.id && stint.status !== "completed").sort((a, b) => a.actualStartAt.localeCompare(b.actualStartAt))[0];
  const manager = canManageEvent(event, activePersona);
  const participants = state.registrations.filter((candidate) => candidate.eventId === event.id && candidate.status !== "withdrawn");
  const name = (id: string) => state.personas.find((persona) => persona.id === id)?.name ?? id;
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <Panel><CalendarClock className="h-5 w-5 text-orange-400" /><span className="mt-3 block text-xs text-gray-500">Race start</span><strong className="mt-1 block text-lg text-white">{formatAmsterdam(event.startAt)}</strong></Panel>
    <Panel><Clock3 className="h-5 w-5 text-orange-400" /><span className="mt-3 block text-xs text-gray-500">Briefing</span><strong className="mt-1 block text-lg text-white">{formatAmsterdam(event.briefingStartAt)}</strong></Panel>
    <Panel><Car className="h-5 w-5 text-orange-400" /><span className="mt-3 block text-xs text-gray-500">Jouw team</span><strong className="mt-1 block text-lg text-white">{team?.name ?? "Nog niet ingedeeld"}</strong></Panel>
    <Panel><CheckCircle2 className="h-5 w-5 text-orange-400" /><span className="mt-3 block text-xs text-gray-500">Volgende actie</span><strong className="mt-1 block text-lg text-white">{nextStint ? "Stints bevestigen" : registration ? "Beschikbaarheid controleren" : manager ? "Planning controleren" : "Aanmelden"}</strong></Panel>
  </div>
  <div className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><Panel><SectionHeading eyebrow="Racebrief" title={event.name} description={`${event.circuit} · ${event.configuration}`} /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-black/20 p-4"><span className="text-xs text-gray-500">Startslots</span><p className="mt-1 font-bold text-gray-200">{event.slots.map((slot) => slot.label).join(", ")}</p></div><div className="rounded-xl bg-black/20 p-4"><span className="text-xs text-gray-500">Klassen waarop gestemd kan worden</span><p className="mt-1 font-bold text-gray-200">{event.classIds.join(" · ")}</p></div><div className="rounded-xl bg-black/20 p-4"><span className="text-xs text-gray-500">Definitieve auto</span><p className="mt-1 font-bold text-gray-200">{event.selectedClassId && getEnduranceCar(event.selectedCarId) ? `${event.selectedClassId} · ${getEnduranceCar(event.selectedCarId)?.name}` : "Nog niet bevestigd"}</p></div></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500/[0.06] p-3 text-sm text-emerald-200 ring-1 ring-emerald-500/15"><ShieldCheck className="h-4 w-4" /> Deze raceomgeving is alleen zichtbaar voor deelnemers en aangewezen managers.</div></Panel>
  <Panel><SectionHeading title="Jouw status" />{registration ? <div className="space-y-3"><StatusPill tone={registration.status === "confirmed" ? "green" : "orange"}>{registration.status}</StatusPill><div className="text-sm text-gray-400"><p>Klasse: <strong className="text-gray-200">{registration.classPreference}</strong></p><p>Autostem: <strong className="text-gray-200">{getEnduranceCar(registration.preferredCarId)?.name ?? "Onbekend"}</strong></p><p>Max. stints: <strong className="text-gray-200">{registration.maxStints}</strong></p></div></div> : <p className="text-sm text-gray-500">Je beheert deze race zonder coureursinschrijving.</p>}</Panel></div>
  <VehicleVotePanel event={event} />
  {manager && <Panel><SectionHeading eyebrow="Privé" title="Deelnemersbeheer" description="Verwijderen trekt onmiddellijk de toegang tot deze raceomgeving in, behalve voor aangewezen managers." /><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="pb-3">Coureur</th><th>Status</th><th>Klasse</th><th>Auto</th><th>Start/finish</th></tr></thead><tbody className="divide-y divide-white/5">{participants.map((participant) => <tr key={participant.id}><td className="py-3 font-bold text-white">{name(participant.userId)}</td><td><select className={`${inputClass} min-h-8 w-44 py-1`} value={participant.status} onChange={(e) => dispatch({ type: "upsert_registration", registration: { ...participant, status: e.target.value as RegistrationStatus } })}><option value="interest">Interesse</option><option value="provisional">Voorlopig</option><option value="confirmed">Definitief</option><option value="reserve">Reserve</option><option value="rejected">Afgewezen</option><option value="withdrawn">Teruggetrokken</option></select></td><td className="text-gray-400">{participant.classPreference}</td><td className="text-gray-400">{getEnduranceCar(participant.preferredCarId)?.name ?? participant.preferredCarId}</td><td className="text-gray-500">{participant.willingToStart ? "Start" : "—"} / {participant.willingToFinish ? "Finish" : "—"}</td></tr>)}</tbody></table></div></Panel>}
  </div>;
};
