import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, History, Play, WandSparkles } from "lucide-react";
import { useEnduranceStore } from "../core/EnduranceStore";
import { makeId } from "../core/actions";
import { canManageEvent, canManageTeam, planningWarnings } from "../core/selectors";
import type { EnduranceEvent, EnduranceStint } from "../core/types";
import { Field, inputClass, Panel, PrimaryButton, SecondaryButton, SectionHeading, StatusPill } from "../shared/ui";
import { generateStints } from "./stintGenerator";
import { StintTimeline } from "./StintTimeline";

const shift = (iso: string, minutes: number) => new Date(new Date(iso).getTime() + minutes * 60_000).toISOString();

export const StintPlanner = ({ event }: { event: EnduranceEvent }) => {
  const { state, activePersona, dispatch } = useEnduranceStore();
  const accessibleTeams = state.teams.filter((team) => team.eventId === event.id && (canManageEvent(event, activePersona) || team.managerId === activePersona.id || state.teamMembers.some((member) => member.teamId === team.id && member.userId === activePersona.id)));
  const [teamId, setTeamId] = useState(accessibleTeams[0]?.id ?? ""); const [tankMinutes, setTankMinutes] = useState(90); const [snap, setSnap] = useState(15); const [message, setMessage] = useState("");
  const team = accessibleTeams.find((candidate) => candidate.id === teamId);
  const stints = state.stints.filter((stint) => stint.eventId === event.id && stint.teamId === teamId);
  const editable = Boolean(team && canManageTeam(state, team, activePersona));
  const warnings = planningWarnings(state, event.id, teamId);
  const versions = state.planningVersions.filter((version) => version.eventId === event.id && version.teamId === teamId).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const latest = versions[0];
  const confirmation = latest && state.confirmations.find((candidate) => candidate.versionId === latest.id && candidate.userId === activePersona.id);
  const teamPeople = useMemo(() => state.personas.filter((persona) => state.teamMembers.some((member) => member.teamId === teamId && member.userId === persona.id)), [state.personas, state.teamMembers, teamId]);

  const generate = () => { if (!team) return; const next = generateStints(state, event, team.id, tankMinutes); if (!next.length) { setMessage("Voeg eerst coureurs toe aan deze auto."); return; } dispatch({ type: "replace_team_stints", eventId: event.id, teamId: team.id, stints: next }); setMessage("Nieuw automatisch voorstel gemaakt."); };
  const move = (stint: EnduranceStint, startAt: string) => { const duration = new Date(stint.actualEndAt).getTime() - new Date(stint.actualStartAt).getTime(); const endAt = new Date(new Date(startAt).getTime() + duration).toISOString(); dispatch({ type: "upsert_stint", stint: { ...stint, originalStartAt: startAt, originalEndAt: endAt, actualStartAt: startAt, actualEndAt: endAt, status: "draft" } }); };
  const resize = (stint: EnduranceStint, delta: number) => { const endAt = shift(stint.actualEndAt, delta); if (new Date(endAt).getTime() - new Date(stint.actualStartAt).getTime() < 5 * 60_000 || new Date(endAt) > new Date(event.endAt)) return; dispatch({ type: "upsert_stint", stint: { ...stint, originalEndAt: endAt, actualEndAt: endAt, status: "draft" } }); };
  const copy = (stint: EnduranceStint) => { const duration = (new Date(stint.actualEndAt).getTime() - new Date(stint.actualStartAt).getTime()) / 60_000; const startAt = stint.actualEndAt; const endAt = shift(startAt, duration); if (new Date(endAt) > new Date(event.endAt)) { setMessage("Er is na deze stint niet genoeg ruimte voor een kopie."); return; } dispatch({ type: "upsert_stint", stint: { ...stint, id: makeId("stint"), originalStartAt: startAt, originalEndAt: endAt, actualStartAt: startAt, actualEndAt: endAt, status: "draft", notes: `${stint.notes} · kopie` } }); };
  const publish = () => { const createdAt = new Date().toISOString(); const versionId = makeId("version"); const users = [...new Set(stints.map((stint) => stint.driverId))]; dispatch({ type: "publish_plan", version: { id: versionId, eventId: event.id, teamId, label: `Versie ${versions.filter((version) => version.teamId === teamId).length + 1}`, createdAt, createdBy: activePersona.id, published: true, stints: stints.map((stint) => ({ ...stint })) }, confirmations: users.map((userId) => ({ id: makeId("confirm"), eventId: event.id, versionId, userId, status: "unseen", note: "", updatedAt: createdAt })), notifications: users.map((userId) => ({ id: makeId("notification"), userId, eventId: event.id, type: "confirmation_needed", title: "Stintplanning gepubliceerd", message: "Bekijk en bevestig je toegewezen stints.", privatePath: `/endurance/races/${event.id}/stints`, read: false, createdAt, discordStatus: "disabled" })) }); setMessage("Planning gepubliceerd en bevestigingen aangevraagd."); };
  const confirm = (status: "accepted" | "change_requested") => latest && dispatch({ type: "confirm_plan", eventId: event.id, versionId: latest.id, userId: activePersona.id, status, note: status === "change_requested" ? "Neem contact op over mijn planning." : "Akkoord", updatedAt: new Date().toISOString() });

  if (!accessibleTeams.length) return <Panel><SectionHeading title="Stintplanner" description="Je bent nog niet aan een auto gekoppeld. Een manager kan je via Team Builder indelen." /></Panel>;
  return <div className="space-y-5"><Panel><SectionHeading eyebrow="Centrale planning" title="Stintplanner" description="Sleep, vergroot, verklein, publiceer en herstel stints. Originele en actuele tijden blijven afzonderlijk bewaard." action={editable && <div className="flex gap-2"><PrimaryButton onClick={generate}><WandSparkles className="h-4 w-4" /> Voorstel genereren</PrimaryButton><SecondaryButton onClick={publish} disabled={!stints.length}><Play className="h-4 w-4" /> Publiceren</SecondaryButton></div>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><Field label="Auto / team"><select className={inputClass} value={teamId} onChange={(e) => setTeamId(e.target.value)}>{accessibleTeams.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} #{candidate.carNumber}</option>)}</select></Field>{editable && <><Field label="Tankduur"><select className={inputClass} value={tankMinutes} onChange={(e) => setTankMinutes(Number(e.target.value))}><option value={45}>45 minuten</option><option value={60}>60 minuten</option><option value={90}>90 minuten</option></select></Field><Field label="Snap"><select className={inputClass} value={snap} onChange={(e) => setSnap(Number(e.target.value))}><option value={5}>5 minuten</option><option value={10}>10 minuten</option><option value={15}>15 minuten</option></select></Field></>}</div>
    <StintTimeline event={event} stints={stints} personas={teamPeople} availability={state.availability.filter((block) => block.eventId === event.id)} editable={editable} snapMinutes={snap} onMove={move} onResize={resize} onDelete={(id) => dispatch({ type: "delete_stint", id })} onCopy={copy} />
    {message && <p role="status" className="mt-3 text-sm text-orange-200">{message}</p>}
  </Panel>
  <div className="grid gap-5 lg:grid-cols-2"><Panel><SectionHeading title="Waarschuwingen" description="Harde conflicten moeten vóór publicatie worden opgelost." />{warnings.length ? <div className="space-y-2">{warnings.map((warning) => <div key={warning.id} className={`flex gap-2 rounded-xl p-3 text-sm ring-1 ${warning.level === "hard" ? "bg-red-500/10 text-red-200 ring-red-500/20" : "bg-amber-500/10 text-amber-200 ring-amber-500/20"}`}><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{warning.message}</div>)}</div> : <div className="flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4" /> Geen planningsconflicten.</div>}</Panel>
  <Panel><SectionHeading title="Versies & bevestiging" description="Iedere publicatie is herstelbaar. Coureurs bevestigen alleen de nieuwste versie." />{latest && <div className="mb-4 rounded-xl bg-black/20 p-3 text-sm"><div className="flex items-center justify-between"><strong className="text-white">{latest.label}</strong><StatusPill tone="green">Gepubliceerd</StatusPill></div>{confirmation && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="text-gray-400">Jouw status: {confirmation.status}</span><PrimaryButton onClick={() => confirm("accepted")} className="min-h-8 px-3 py-1 text-xs">Akkoord</PrimaryButton><SecondaryButton onClick={() => confirm("change_requested")} className="min-h-8 px-3 py-1 text-xs">Wijziging vragen</SecondaryButton></div>}</div>}<div className="space-y-2">{versions.map((version) => <div key={version.id} className="flex items-center justify-between rounded-xl bg-white/[0.035] p-3 text-sm"><div><strong className="text-gray-200">{version.label}</strong><p className="text-xs text-gray-500">{new Date(version.createdAt).toLocaleString("nl-NL")}</p></div>{editable && <SecondaryButton onClick={() => dispatch({ type: "restore_plan", versionId: version.id })} className="min-h-8 px-3 py-1 text-xs"><History className="h-3.5 w-3.5" /> Herstellen</SecondaryButton>}</div>)}</div>{!versions.length && <p className="text-sm text-gray-500">Nog geen gepubliceerde versies.</p>}</Panel></div></div>;
};
